
GET http://localhost:8080/user HTTP/1.1
content-type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImI2ZjYxMGE5LTYyNWItNGFlOS1hNDhhLTBhNDJjNGIyMGJjNyIsIm5hbWUiOiJHYWJyaWVsIiwiY3BmIjoiMzgyMDk5NDg4MjIiLCJtYW5hZ2VyIjp0cnVlLCJiYWxhbmNlIjoiMC4wMCIsImNsaWVudEJhbGFuY2UiOiIwLjAwIiwicGFyZW50QWNjb3VudCI6eyJpZCI6Ijk4ZGE4YTgwLWFhNDgtNDJhNy05NzI5LTg3MjlmMmFiMDU1YiIsInVzZXJOYW1lIjoiR2FicmllbCBDYW1wb3MiLCJ1c2VyQ3BmIjoic3RybmciLCJjcmVhdGVkQXQiOiIyMDA3LTA5LTI0VDE1OjUzOjM3LjIxNloiLCJwaXhLZXkiOnsia2V5IjoiUGl4S2V5Iiwic3RhdHVzIjoiYWN0aXZlIn0sImlkU2VsbGVyIjoiMTBiZTllMTgtYzgzMi00NmJkLTk4OGUtZTM5MDkwN2ZjMzJiIiwiYmFsYW5jZSI6IjEwMC4wMCIsInN0YXR1cyI6InN0cmluZyJ9LCJjaGlsZEFjY291bnRzIjpbXSwiaWF0IjoxNzMwMjIxMzM5LCJleHAiOjE3MzAyMjQ5Mzl9.RyOEUlGMSQ0mb6DB1HYPnTA2ZMNPong2xegKcGlbXOc
